targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/**.dart
      json_serializable:
        generate_for:
          include:
            - lib/**.dart
