name: dart_format
description: A formatter for Dart. Like dartfmt. But better ;) Because it's configurable.
homepage: https://github.com/eggnstone/dart_format
version: 1.3.1
topics:
  - code-style
  - formatting

environment:
  sdk: ^3.0.0

executables:
  dart_format:
  dartformat: dart_format

dependencies:
  analyzer: ^7.3.0
  eggnstone_dart: ^1.2.3
  freezed_annotation: ^2.4.4
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mime: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  meta: ^1.16.0
  test: any

dependency_overrides:
  #

assets:
  - assets/favicon.ico
