name: dart_format
description: A formatter for Dart. Like dartfmt. But better ;) Because it's configurable.
homepage: https://github.com/eggnstone/dart_format
version: 1.1.20
topics:
  - code-style
  - formatting

environment:
  sdk: ^3.0.0

executables:
  dart_format:
  dartformat: dart_format

dependencies:
  # So, because no versions of _macros from sdk match 0.3.2 and dart_format depends on analyzer ^6.8.0, version solving failed.
  analyzer: ^6.5.0
  eggnstone_dart: ^1.1.0
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mime: ^1.0.5

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  meta: ^1.15.0
  test: ^1.25.8

assets:
  - assets/favicon.ico
