name: dart_format
description: A formatter for Dart. Like dartfmt. But better ;) Because it's configurable.
homepage: https://github.com/eggnstone/dart_format
version: 1.2.0
topics:
  - code-style
  - formatting

environment:
  sdk: ^3.0.0

executables:
  dart_format:
  dartformat: dart_format

dependencies:
  analyzer: ^6.8.0
  eggnstone_dart: ^1.1.1
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  mime: ^2.0.0

dependency_overrides:
  #analyzer: ^7.0.0
  #macros: ^0.3.3

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  meta: ^1.16.0
  test: any

assets:
  - assets/favicon.ico
