name: dart_format
description: A formatter for Dart. Like dartfmt. But better ;) Because it's configurable.
homepage: https://pub.dev/publishers/eggnstone.dev/packages

version: 0.0.4

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  eggnstone_dart: ^1.0.0

dev_dependencies:
  test: ^1.23.1
