name: dart_format
description: A formatter for Dart. Like dartfmt. But better ;) Because it's configurable.
homepage: https://github.com/eggnstone/dart_format
version: 1.4.1
topics:
  - code-style
  - formatting

environment:
  sdk: ^3.0.0

executables:
  dart_format:
  dartformat: dart_format

dependencies:
  analyzer: ^7.4.5
  freezed_annotation: ^3.0.0
  eggnstone_dart: ^1.4.1
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mime: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  meta: ^1.17.0
  test: any

dependency_overrides:
  #

assets:
  - assets/favicon.ico
