name: dart_format
description: A formatter for Dart. Like dartfmt. But better ;) Because it's configurable.
homepage: https://pub.dev/publishers/eggnstone.dev/packages

version: 0.0.2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:

dev_dependencies:
  build_runner: ^2.3.3
  test: ^1.23.1
