name: dart_format
description: A formatter for Dart. Like dartfmt. But better ;) Because it's configurable.

version: 0.0.1+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
