name: dart_format
description: A formatter for Dart. Like dartfmt. But better ;) Because it's configurable.
homepage: https://github.com/eggnstone/dart_format

version: 1.1.5

environment:
  sdk: ^3.0.0

executables:
  dart_format:
  dartformat: dart_format

dependencies:
  analyzer: ^6.4.1
  eggnstone_dart: ^1.1.0
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  mime: ^1.0.5

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  meta: ^1.12.0
  test: ^1.25.2

assets:
  - assets/favicon.ico
