name: dart_format
description: A formatter for Dart. Like dartfmt. But better ;) Because it's configurable.
homepage: https://pub.dev/publishers/eggnstone.dev/packages

version: 0.0.5

environment:
  sdk: '>=2.19.0 <3.0.0'

executables:
  dart_format:
  dartformat: dart_format

dependencies:
  #dotlin:
    #path: ../../../GitHub/dotlin/packages/dotlin
    #git:
    #  url: https://github.com/dotlin-org/dotlin.git
    #  path: packages/dotlin
    #  ref: 0472fb138603996ee70df2c7dcb5ee6e243328c3
  eggnstone_dart: ^1.0.0

dev_dependencies:
  #dotlin_generator:
    #path: ../../../GitHub/dotlin/packages/dotlin_generator
    #git:
    #  url: https://github.com/dotlin-org/dotlin.git
    #  path: packages/dotlin_generator
    #  ref: 0472fb138603996ee70df2c7dcb5ee6e243328c3
  test: ^1.23.1
